export const sportsArray = [
  "Football (Soccer)",
  "Basketball",
  "American Football",
  "Rugby (Union)",
  "Rugby (League)",
  "Cricket",
  "Ice Hockey",
  "Field Hockey",
  "Volleyball",
  "Handball",
  "Water Polo",
  "Athletics (Track and Field)",
  "Swimming",
  "Gymnastics",
  "Tennis",
  "Golf",
  "Boxing",
  "Wrestling",
  "Martial Arts",
  "Cycling (Road)",
  "Cycling (Mountain)",
  "Cycling (Track)",
  "Cycling (BMX)",
  "Archery",
  "Badminton",
  "Table Tennis",
  "Squash",
  "Mixed Martial Arts (MMA)",
  "Judo",
  "Karate",
  "Taekwondo",
  "Diving",
  "Synchronized Swimming",
  "Rowing",
  "Canoeing",
  "Kayaking",
  "Sailing",
  "Windsurfing",
  "Alpine Skiing",
  "Nordic Skiing",
  "Freestyle Skiing",
  "Snowboarding",
  "Figure Skating",
  "Speed Skating",
  "Curling",
  "Bobsleigh",
  "Luge",
  "Skeleton",
  "Rock Climbing",
  "Surfing",
  "Skateboarding",
  "Skydiving",
  "Base Jumping",
  "Whitewater Rafting",
  "Parkour",
  "Formula 1 Racing",
  "MotoGP",
  "Rally Racing",
  "NASCAR",
  "Karting",
  "Horse Racing",
  "Show Jumping",
  "Dressage",
  "Eventing",
  "Polo",
  "Archery",
  "Shooting (Rifle)",
  "Shooting (Pistol)",
  "Skeet Shooting",
  "Trap Shooting",
  // Add more sports here...
];
export const interestList = [
  "Football (Soccer)",
  "Basketball",
  "American Football",
  "Rugby (Union)",
  "Rugby (League)",
  "Cricket",
  "Ice Hockey",
  "Field Hockey",
  "Volleyball",
  "Handball",
  "Water Polo",
  "Athletics (Track and Field)",
  "Swimming",
  "Gymnastics",
  "Tennis",
  "Golf",
  "Boxing",
  "Wrestling",
  "Martial Arts",
  "Cycling (Road)",
  "Cycling (Mountain)",
  "Cycling (Track)",
  "Cycling (BMX)",
  "Archery",
  "Badminton",
  "Table Tennis",
  "Squash",
  "Mixed Martial Arts (MMA)",
  "Judo",
  "Karate",
  "Taekwondo",
  "Diving",
  "Synchronized Swimming",
  "Rowing",
  "Canoeing",
  "Kayaking",
  "Sailing",
  "Windsurfing",
  "Alpine Skiing",
  "Nordic Skiing",
  "Freestyle Skiing",
  "Snowboarding",
  "Figure Skating",
  "Speed Skating",
  "Curling",
  "Bobsleigh",
  "Luge",
  "Skeleton",
  "Rock Climbing",
  "Surfing",
  "Skateboarding",
  "Skydiving",
  "Base Jumping",
  "Whitewater Rafting",
  "Parkour",
  "Formula 1 Racing",
  "MotoGP",
  "Rally Racing",
  "NASCAR",
  "Karting",
  "Horse Racing",
  "Show Jumping",
  "Dressage",
  "Eventing",
  "Polo",
  "Archery",
  "Shooting (Rifle)",
  "Shooting (Pistol)",
  "Skeet Shooting",
  "Trap Shooting",
  // Add more sports here...
];
export const defaultImg =
  "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80";
