export const sportsArray = [
  "Football (Soccer)",
  "Basketball",
  "American Football",
  "Rugby (Union)",
  "Rugby (League)",
  "Cricket",
  "Ice Hockey",
  "Field Hockey",
  "Volleyball",
  "Handball",
  "Water Polo",
  "Athletics (Track and Field)",
  "Swimming",
  "Gymnastics",
  "Tennis",
  "Golf",
  "Boxing",
  "Wrestling",
  "Martial Arts",
  "Cycling (Road)",
  "Cycling (Mountain)",
  "Cycling (Track)",
  "Cycling (BMX)",
  "Archery",
  "Badminton",
  "Table Tennis",
  "Squash",
  "Mixed Martial Arts (MMA)",
  "Judo",
  "Karate",
  "Taekwondo",
  "Diving",
  "Synchronized Swimming",
  "Rowing",
  "Canoeing",
  "Kayaking",
  "Sailing",
  "Windsurfing",
  "Alpine Skiing",
  "Nordic Skiing",
  "Freestyle Skiing",
  "Snowboarding",
  "Figure Skating",
  "Speed Skating",
  "Curling",
  "Bobsleigh",
  "Luge",
  "Skeleton",
  "Rock Climbing",
  "Surfing",
  "Skateboarding",
  "Skydiving",
  "Base Jumping",
  "Whitewater Rafting",
  "Parkour",
  "Formula 1 Racing",
  "MotoGP",
  "Rally Racing",
  "NASCAR",
  "Karting",
  "Horse Racing",
  "Show Jumping",
  "Dressage",
  "Eventing",
  "Polo",
  "Archery",
  "Shooting (Rifle)",
  "Shooting (Pistol)",
  "Skeet Shooting",
  "Trap Shooting",
  // Add more sports here...
];
export const interestList = [
  "None",
  "Football (Soccer)",
  "Basketball",
  "American Football",
  "Rugby (Union)",
  "Rugby (League)",
  "Cricket",
  "Ice Hockey",
  "Field Hockey",
  "Volleyball",
  "Handball",
  "Water Polo",
  "Athletics (Track and Field)",
  "Swimming",
  "Gymnastics",
  "Tennis",
  "Golf",
  "Boxing",
  "Wrestling",
  "Martial Arts",
  "Cycling (Road)",
  "Cycling (Mountain)",
  "Cycling (Track)",
  "Cycling (BMX)",
  "Archery",
  "Badminton",
  "Table Tennis",
  "Squash",
  "Mixed Martial Arts (MMA)",
  "Judo",
  "Karate",
  "Taekwondo",
  "Diving",
  "Synchronized Swimming",
  "Rowing",
  "Canoeing",
  "Kayaking",
  "Sailing",
  "Windsurfing",
  "Alpine Skiing",
  "Nordic Skiing",
  "Freestyle Skiing",
  "Snowboarding",
  "Figure Skating",
  "Speed Skating",
  "Curling",
  "Bobsleigh",
  "Luge",
  "Skeleton",
  "Rock Climbing",
  "Surfing",
  "Skateboarding",
  "Skydiving",
  "Base Jumping",
  "Whitewater Rafting",
  "Parkour",
  "Formula 1 Racing",
  "MotoGP",
  "Rally Racing",
  "NASCAR",
  "Karting",
  "Horse Racing",
  "Show Jumping",
  "Dressage",
  "Eventing",
  "Polo",
  "Archery",
  "Shooting (Rifle)",
  "Shooting (Pistol)",
  "Skeet Shooting",
  "Trap Shooting",
  // Add more sports here...
];

export const commonDiseases = [
  "None",
  "Diabetes",
  "Hypertension (High Blood Pressure)",
  "Influenza (Flu)",
  "Asthma",
  "Arthritis",
  "Coronary Artery Disease",
  "Stroke",
  "Chronic Obstructive Pulmonary Disease (COPD)",
  "Alzheimer's Disease",
  "Parkinson's Disease",
  "Depression",
  "Anxiety Disorders",
  "Osteoporosis",
  "Cancer (Various Types)",
  "Heart Failure",
  "Chronic Kidney Disease",
  "Gastroesophageal Reflux Disease (GERD)",
  "Chronic Liver Disease",
  "Migraine",
  "Eczema",
  "Psoriasis",
  "Multiple Sclerosis",
  "Glaucoma",
  "Rheumatoid Arthritis",
  "Chronic Fatigue Syndrome",
  "Irritable Bowel Syndrome (IBS)",
  "Bipolar Disorder",
  "Schizophrenia",
  "Chronic Bronchitis",
  "Peptic Ulcer Disease",
  "Thyroid Disorders",
  "Allergies",
  "Anemia",
  "Gout",
  "Pneumonia",
  "Urinary Tract Infection (UTI)",
  "Epilepsy",
  "Hypothyroidism",
  "Hyperthyroidism",
  "Endometriosis",
  "Polycystic Ovary Syndrome (PCOS)",
  "Hemorrhoids",
  "Gastroenteritis",
  "Tuberculosis (TB)",
  "Cholecystitis (Gallbladder Inflammation)",
  "Ovarian Cancer",
  "Prostate Cancer",
  "Melanoma",
  "Pancreatitis",
  "Crohn's Disease",
  "Ulcerative Colitis",
  "Osteoarthritis",
  "Glomerulonephritis",
  "Leukemia",
  "Hepatitis",
  "Meningitis",
  "Cataracts",
  "Retinal Diseases",
  "Fibromyalgia",
  "Osteomyelitis",
  "Atherosclerosis",
  "Atrial Fibrillation",
  "Deep Vein Thrombosis (DVT)",
  "Pulmonary Embolism (PE)",
  "Hemorrhagic Stroke",
  "Jaundice",
  "Congestive Heart Failure",
  "Obsessive-Compulsive Disorder (OCD)",
  "Panic Disorder",
  "Sleep Apnea",
  "Insomnia",
  "Myocardial Infarction (Heart Attack)",
  "Acne",
  "Bipolar Disorder",
  "Hypertensive Heart Disease",
  "Type 2 Diabetes",
  "Temporomandibular Joint Disorder (TMJ)",
  "Celiac Disease",
  "Polio",
  "Measles",
  "Chickenpox",
  "Rubella (German Measles)",
  "Pertussis (Whooping Cough)",
  "Dengue Fever",
  "Tuberculosis (TB)",
  "Malaria",
  "Cholera",
  "Zika Virus",
  "Yellow Fever",
  "Typhoid Fever",
  "HIV/AIDS",
  "Hepatitis B",
  "Syphilis",
  "Gonorrhea",
  "Chlamydia",
  "Herpes",
  "Human Papillomavirus (HPV)",
  "Inflammatory Bowel Disease",
  "Systemic Lupus Erythematosus (Lupus)",
  "E. coli Infection",
];

console.log(commonDiseases);

export const defaultImg =
  "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png";
